name: "Synopsys Security Scan (SAST)"

on:
  workflow_call:
    inputs:
      POLARIS_DOWNLOAD_URL:
        required: false
        type: string
        default: https://compono.polaris.synopsys.com/api/tools/v2/downloads/polaris_cli-linux64-2022.3.0.zip
      POLARIS_SERVER_URL:
        required: true
        type: string
      BUILD_COMMAND:
        required: false
        type: string
        default: "make build"
      CLEAN_COMMAND:
        required: false
        type: string
        default: "make,clean"
    secrets:
      POLARIS_ACCESS_TOKEN:
        required: true
      NPM_TOKEN:
        required: true
      GH_PACKAGES_TOKEN:
        required: true
    
jobs:
  security:
    name: Synopsys Security Scan (SAST)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Execute the Synopys Detect script
      run: |
        curl -L ${{ inputs.POLARIS_DOWNLOAD_URL }} -o polaris_cli.zip
        unzip polaris_cli.zip
        export POLARIS_SERVER_URL=${{ inputs.POLARIS_SERVER_URL }}
        export POLARIS_ACCESS_TOKEN=${{ secrets.POLARIS_ACCESS_TOKEN }}
        export GIT_BRANCH=${{ github.head_ref }}
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" >> ~/.npmrc
        chmod +x ./polaris_cli-linux64-2022.3.0/bin/polaris
        ./polaris_cli-linux64-2022.3.0/bin/polaris --co capture.build.cleanCommands="[{shell:[${{ inputs.CLEAN_COMMAND }}]}]" analyze -w --coverity-ignore-capture-failure	-- ${{ inputs.BUILD_COMMAND }}
        cat /home/runner/work/admin-ui/admin-ui/polaris.yml