name: "Synopsys Security Scan (SAST)"

on:
  workflow_call:
    # inputs:
    #   BLACKDUCK_URL:
    #     required: true
    #     type: string
    #   PROJECT_NAME:
    #     required: true
    #     type: string
    #   APPLICATION_NAME:
    #     required: true
    #     type: string
    #   POLICY_NAME:
    #     required: true
    #     type: string
    #   SCAN_TYPE:
    #     required: false
    #     type: string
    #     default: RAPID
    secrets:
      POLARIS_ACCESS_TOKEN:
        required: true
    
jobs:
  security:
    name: Synopsys Security Scan (SAST)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print workflow input variables
      run: |
        echo "Secret POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}"

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Execute the Synopys Detect script
      run: |
        bash <(curl -s -L https://detect.synopsys.com/detect7.sh --polaris.access.token=${{ secrets.POLARIS_ACCESS_TOKEN }})